'use strict';
// usamos el bloque try-catch para evitar errores
try{
   let x= 21;  // lo traemos con alt + flecha hacia arriba o abajo
    mifuncion();
}
catch(error){ // catchamos el error
    console.log(error);
 
}

finally{
    console.log('termina la revision de errores');
}
//la ejecucion ahora continua

